# Generated by Django 5.2.11 on 2026-03-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Categoría de material',
                'verbose_name_plural': 'Categorías de materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECIBIDA', 'Recibida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20, verbose_name='Estado de pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Fórmula Franela básica', max_length=150, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('costo_mano_obra_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Opcional. Si no aplica, déjalo en 0.', max_digits=12, verbose_name='Costo mano de obra (por unidad)')),
                ('costo_indirecto_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Opcional. Ej: electricidad, desgaste, etc.', max_digits=12, verbose_name='Costo indirecto (por unidad)')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Fórmula',
                'verbose_name_plural': 'Fórmulas',
                'ordering': ['variante_producto__producto__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='inventario__nombre_8f71a9_idx'), models.Index(fields=['activo'], name='inventario__activo_cac698_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('VENCIDA', 'Vencida')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='inventario.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagarCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('VENCIDA', 'Vencida')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='inventario.compra', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Cuenta por pagar (Compra)',
                'verbose_name_plural': 'Cuentas por pagar (Compras)',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20, verbose_name='Estado de pago')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='inventario.categoriagasto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagarGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('VENCIDA', 'Vencida')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='inventario.gasto', verbose_name='Gasto')),
            ],
            options={
                'verbose_name': 'Cuenta por pagar (Gasto)',
                'verbose_name_plural': 'Cuentas por pagar (Gastos)',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('unidad', models.CharField(help_text='Ej: metro, unidad, gramo, litro', max_length=50, verbose_name='Unidad')),
                ('costo_defecto', models.DecimalField(decimal_places=2, default=0, help_text='Costo referencial si no quieres calcularlo desde compras.', max_digits=12, verbose_name='Costo (por defecto)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='inventario.categoriamaterial', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('PRODUCTO', 'Producto terminado')], max_length=20, verbose_name='Tipo')),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima para alertas (opcional).', max_digits=12, verbose_name='Punto de reorden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventario.almacen', verbose_name='Almacén')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_inventario', to='inventario.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Ítem de inventario',
                'verbose_name_plural': 'Ítems de inventario',
                'ordering': ['tipo', 'almacen__nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=4, help_text='Cuánto material se usa para producir 1 unidad del producto.', max_digits=12, verbose_name='Cantidad por unidad')),
                ('merma_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Opcional. Ej: 5.00 significa 5% extra.', max_digits=5, verbose_name='Merma (%)')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.formula', verbose_name='Fórmula')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_formula', to='inventario.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Detalle de fórmula',
                'verbose_name_plural': 'Detalles de fórmula',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo unitario')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.compra', verbose_name='Compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('TRASLADO', 'Traslado')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Para ENTRADAS suele ser obligatorio. Para SALIDAS es opcional si calculas COGS aparte.', max_digits=12, null=True, verbose_name='Costo unitario')),
                ('referencia', models.CharField(blank=True, help_text='Ej: COMPRA, VENTA, PRODUCCION, AJUSTE', max_length=50, null=True, verbose_name='Referencia')),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID referencia')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.iteminventario', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('ENTRADA', 'Entrada (cobro)'), ('SALIDA', 'Salida (pago)')], max_length=20, verbose_name='Dirección')),
                ('metodo', models.CharField(blank=True, help_text='Efectivo, transferencia, etc.', max_length=50, null=True, verbose_name='Método')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('cuenta_por_cobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='inventario.cuentaporcobrar', verbose_name='Cuenta por cobrar')),
                ('cuenta_por_pagar_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='inventario.cuentaporpagarcompra', verbose_name='Cuenta por pagar (Compra)')),
                ('cuenta_por_pagar_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='inventario.cuentaporpagargasto', verbose_name='Cuenta por pagar (Gasto)')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_venta_defecto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de venta (por defecto)')),
                ('controla_inventario', models.BooleanField(default=True, verbose_name='Controla inventario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoriaproducto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='inventario__nombre_70461d_idx'), models.Index(fields=['activo'], name='inventario__activo_f76b65_idx')],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='cuentaporpagargasto',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Opcional: si el gasto no tiene proveedor, puedes dejarlo vacío.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar_gasto', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='cuentaporpagarcompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar_compra', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre de variante')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Si lo dejas vacío, se usa el precio por defecto del producto.', max_digits=12, null=True, verbose_name='Precio de venta')),
                ('modo_costo', models.CharField(choices=[('FIJO', 'Costo fijo'), ('FORMULA', 'Por fórmula')], default='FIJO', max_length=10, verbose_name='Modo de costo')),
                ('costo_unitario_fijo', models.DecimalField(blank=True, decimal_places=2, help_text="Solo aplica si el modo de costo es 'Costo fijo'.", max_digits=12, null=True, verbose_name='Costo unitario fijo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de productos',
                'ordering': ['producto__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='variante_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_inventario', to='inventario.varianteproducto', verbose_name='Variante de producto'),
        ),
        migrations.AddField(
            model_name='formula',
            name='variante_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='inventario.varianteproducto', verbose_name='Variante de producto'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=20, verbose_name='Tipo de pago')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo pendiente')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cliente', models.ForeignKey(blank=True, help_text='Opcional: si no hay cliente, puede ser venta general.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('costo_unitario_al_vender', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo unitario (al vender)')),
                ('variante_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.varianteproducto', verbose_name='Variante de producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_cobrar', to='inventario.venta', verbose_name='Venta'),
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad producida')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONSUMIDO', 'Material consumido'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('costo_mano_obra_real', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo mano de obra (real)')),
                ('costo_indirecto_real', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo indirecto (real)')),
                ('costo_unitario_resultado', models.DecimalField(decimal_places=2, default=0, help_text='Se calculará cuando implementemos el servicio de producción.', max_digits=12, verbose_name='Costo unitario resultante')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.formula', verbose_name='Fórmula')),
            ],
            options={
                'verbose_name': 'Lote de producción',
                'verbose_name_plural': 'Lotes de producción',
                'ordering': ['-fecha', '-creado'],
                'indexes': [models.Index(fields=['fecha'], name='inventario__fecha_3db026_idx'), models.Index(fields=['estado'], name='inventario__estado_0ee0d5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['nombre'], name='inventario__nombre_f13d73_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['activo'], name='inventario__activo_9efa5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='uq_material_categoria_nombre'),
        ),
        migrations.AddConstraint(
            model_name='detalleformula',
            constraint=models.UniqueConstraint(fields=('formula', 'material'), name='uq_detalleformula_formula_material'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='inventario__tipo_b85d84_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['referencia', 'referencia_id'], name='inventario__referen_3b490e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['creado'], name='inventario__creado_0a102f_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha'], name='inventario__fecha_ef3b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['direccion'], name='inventario__direcci_b8a77b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='inventario__activo_041dee_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='uq_producto_categoria_nombre'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['fecha'], name='inventario__fecha_01a025_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['estado_pago'], name='inventario__estado__b49dad_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagargasto',
            index=models.Index(fields=['estado'], name='inventario__estado_dbda5e_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagargasto',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_071aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagarcompra',
            index=models.Index(fields=['estado'], name='inventario__estado_9c713e_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporpagarcompra',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_2b150a_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['fecha'], name='inventario__fecha_ecf680_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado'], name='inventario__estado_45e86c_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado_pago'], name='inventario__estado__c0863e_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['sku'], name='inventario__sku_c86daf_idx'),
        ),
        migrations.AddIndex(
            model_name='varianteproducto',
            index=models.Index(fields=['activa'], name='inventario__activa_d9ddb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='uq_variante_producto_nombre'),
        ),
        migrations.AddConstraint(
            model_name='iteminventario',
            constraint=models.UniqueConstraint(fields=('almacen', 'material'), name='uq_iteminventario_almacen_material'),
        ),
        migrations.AddConstraint(
            model_name='iteminventario',
            constraint=models.UniqueConstraint(fields=('almacen', 'variante_producto'), name='uq_iteminventario_almacen_variante'),
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['activa'], name='inventario__activa_633f84_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='inventario__fecha_2f5250_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='inventario__estado_964951_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tipo_pago'], name='inventario__tipo_pa_3a3e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['variante_producto'], name='inventario__variant_700d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['estado'], name='inventario__estado_932122_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaporcobrar',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_51b373_idx'),
        ),
    ]
